### PR TITLE
Fix argument encoding

### PR DESCRIPTION
**Pull request by raimohanska**
I noticed that the argument/scope serialization mechanism failed for arrays. I rewrote it into a hopefully more maintainable shape.

Note: The serialization protocol is not compatible with the earlier one, so running with new client code against an older version of server will not work.

### CODE REVIEW

**Comment by raimohanska** [comment]
Also noticed that in the `main` version of serialization, nested objects were stringified multiple times, because of the recursive call to `scopeToString`. That's no longer the case, as encoding and stringification are separated.

**Comment by raimohanska** [comment]
Even with this improvement that adds array support, there'll be failing cases, such as Date objects (will come back as strings) and any other objects that have a prototype other than Object. I would suggest a fail-fast approach and throwing an Error in case the payload contains anything else than primitives (string, number, boolean, null), plain objects, arrays.

**Comment by raimohanska** [comment]
I removed the commits related to #13 from this PR to make this a bit more manageable for you.

**Comment by raimohanska** [comment]
Force pushed a fix: there was an unnecessary file inadvertently included in the commit.

**Comment by markwylde** [comment]
> Even with this improvement that adds array support, there'll be failing cases, such as Date objects (will come back as strings) and any other objects that have a prototype other than Object. I would suggest a fail-fast approach and throwing an Error in case the payload contains anything else than primitives (string, number, boolean, null), plain objects, arrays.

Thanks so much for your contribution. Your refactor into the encode/decode is so much nicer.

I'll get v5 released tonight, along with your other PR's/bug finds.

I like the fail-fast approach, and will help avoid accidents in the future. Though I'm wondering, for dates specifically, we could probably add a new 'date' type and parse it.

**Comment by raimohanska** [comment]
Yes, one could support Date as a special case. Not sure if there are other common special cases. Personally, I might lean to a strict "JSON only" approach here though, as it's easy to communicate to users and stops feature creep.

**Comment by markwylde** [comment]
Yeah 100% agree.

**Pull request merged**
